version: '3.9'
services:
  invoice-ocr:
    build: ./python-invoice-ocr
    container_name: invoice-ocr
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
