version: '3.9'
services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${ASSET_S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${ASSET_S3_SECRET_KEY:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:9000/minio/health/ready || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  minio-init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      - /bin/sh
      - -c
      - >-
        ASSET_BUCKET=${ASSET_S3_BUCKET:-store-assets};
        INVOICE_BUCKET=${INVOICE_S3_BUCKET:-store-invoices};
        mc alias set local http://minio:9000 ${ASSET_S3_ACCESS_KEY:-minioadmin} ${ASSET_S3_SECRET_KEY:-minioadmin}
        && mc mb --ignore-existing local/$${ASSET_BUCKET}
        && mc anonymous set download local/$${ASSET_BUCKET}
        && if [ "$${INVOICE_BUCKET}" != "$${ASSET_BUCKET}" ]; then mc mb --ignore-existing local/$${INVOICE_BUCKET}; fi
    restart: 'no'

  invoice-ocr:
    build: ./python-invoice-ocr
    container_name: invoice-ocr
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC
      - BARCODE_MIN_LENGTH=7
      - BARCODE_MAX_LENGTH=14
      # OCR tuning for scanned PDFs (adjust as needed)
      - OCR_RASTER_DPI=400
      - OCR_REMOVE_LINES=1
      - OCR_PSMS=6,4,12,11,3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  minio-data:
