name: 'Netlify CLI Deploy'
description: 'Deploy to Netlify using the Netlify CLI'
inputs:
  args:
    description: 'Arguments to pass to netlify-cli'
    required: true
runs:
  using: 'docker'
  image: 'docker://netlify/netlify-cli:latest'
  args:
    - sh
    - -c
    - netlify ${{ inputs.args }}
