SELECT TOP (@limit)
  pv.IDTARIFAV AS tariffId,
  a.CODARTICULO AS articleCode,
  a.DESCRIPCION AS description,
  a.REFPROVEEDOR AS refProveedor,
  pv.PBRUTO AS priceGross,
  pv.DTO AS discount,
  pv.PNETO AS priceNet,
  pv.PBRUTO2 AS priceGrossAlt,
  pv.DTO2 AS discountAlt,
  pv.PNETO2 AS priceNetAlt,
  pv.FECHAMODIFICADO AS priceDate,
  st.CODALMACEN AS warehouseCode,
  st.STOCK AS stockQuantity,
  st.FECHAMODIFICADO AS stockDate,
  CursorValue = CASE WHEN pv.FECHAMODIFICADO >= st.FECHAMODIFICADO THEN pv.FECHAMODIFICADO ELSE st.FECHAMODIFICADO END
FROM PRECIOSVENTA pv
JOIN ARTICULOS a ON a.CODARTICULO = pv.CODARTICULO
JOIN STOCKS st ON st.CODARTICULO = a.CODARTICULO
WHERE pv.IDTARIFAV = @tariffId
  AND st.CODALMACEN = @storeCode
  AND a.DESCRIPCION IS NOT NULL
  AND a.DESCRIPCION <> ''
  AND a.DESCRIPCION NOT LIKE '%CM %' 
AND a.DESCRIPCION NOT LIKE '%GM %' 
AND a.DESCRIPCION NOT LIKE '%CL %'
AND a.DESCRIPCION NOT LIKE '%LM %'
AND a.DESCRIPCION NOT LIKE '%LS %'
AND a.DESCRIPCION NOT LIKE '%YM %'
AND a.DESCRIPCION NOT LIKE '%EAT %'
AND a.DESCRIPCION NOT LIKE '%Cl %'
AND a.DESCRIPCION NOT LIKE '%GMT %'
AND a.DESCRIPCION NOT LIKE '%CR %'
AND a.DESCRIPCION NOT LIKE '%HOS %'
AND a.DESCRIPCION NOT LIKE '%CR %'
AND a.DESCRIPCION NOT LIKE '%CRT %'
AND a.DESCRIPCION NOT LIKE '%EAS %'
AND a.DESCRIPCION NOT LIKE '%CS %'
AND a.DESCRIPCION NOT LIKE '%LMT %'
AND a.DESCRIPCION NOT LIKE '%LST %'
AND a.DESCRIPCION NOT LIKE '%YMT %'
AND a.DESCRIPCION NOT LIKE '%CMT %'
AND a.DESCRIPCION NOT LIKE '%CLT %'
AND a.DESCRIPCION NOT LIKE '%CST %'
AND a.DESCRIPCION NOT LIKE '%GWP %'
AND a.DESCRIPCION NOT LIKE '%EM %'
AND a.DESCRIPCION NOT LIKE '%ES %'
AND a.DESCRIPCION NOT LIKE '%GVM %'
AND a.DESCRIPCION NOT LIKE '%GVMT %'
AND a.DESCRIPCION NOT LIKE '%ELT %'
AND a.DESCRIPCION NOT LIKE '%PDC %'
AND a.DESCRIPCION NOT LIKE '%BODY %'
AND a.DESCRIPCION NOT LIKE '%YMP %'
AND a.DESCRIPCION NOT LIKE '%LMP %'
AND a.DESCRIPCION NOT LIKE '%Sample %'
AND a.DESCRIPCION NOT LIKE '%LO %'
AND a.DESCRIPCION NOT LIKE '%LOT %'
AND a.DESCRIPCION NOT LIKE '%VIC %'
AND a.DESCRIPCION NOT LIKE '%TFT %'
AND a.DESCRIPCION NOT LIKE '%GMP %'
AND a.DESCRIPCION NOT LIKE '%PT %'
AND a.DESCRIPCION NOT LIKE '%PDL %'
AND a.DESCRIPCION NOT LIKE '%S Tester %'
AND a.DESCRIPCION NOT LIKE '%CDMT %'
AND a.DESCRIPCION NOT LIKE '%DM Tester %'
AND a.DESCRIPCION NOT LIKE '%MAC %'
AND a.DESCRIPCION NOT LIKE '%CDM %'
AND a.DESCRIPCION NOT LIKE '%DM %'
AND a.DESCRIPCION NOT LIKE '%BU %'
AND a.DESCRIPCION NOT LIKE '%BUT %'
AND a.DESCRIPCION NOT LIKE '%FB %'
AND a.DESCRIPCION NOT LIKE '%FBT %'
AND a.DESCRIPCION NOT LIKE '%FST %'
AND a.DESCRIPCION NOT LIKE '%S TR %'
  AND (
    @cursor IS NULL
    OR (CASE WHEN pv.FECHAMODIFICADO >= st.FECHAMODIFICADO THEN pv.FECHAMODIFICADO ELSE st.FECHAMODIFICADO END) > @cursor
  )
ORDER BY CursorValue ASC, a.CODARTICULO ASC;
