name: CD Backend (Build and Push Image)

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.backend'
      - 'src/**'
      - 'prisma/**'
      - '.github/workflows/cd-backend.yml'

permissions:
  contents: read
  packages: write

jobs:
  build_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/store-backend
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Define image tags
        id: meta
        run: |
          echo "sha_tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          echo "branch_tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.branch_tag }}
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_tag }}
