name: CD OCR (Build and Push Image)

on:
  push:
    branches: [ main ]
    paths:
      - 'python-invoice-ocr/**'
      - '.github/workflows/cd-ocr.yml'

permissions:
  contents: read
  packages: write

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push OCR image
        uses: docker/build-push-action@v6
        with:
          context: ./python-invoice-ocr
          file: ./python-invoice-ocr/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/invoice-ocr:latest

